<?php
/**
 * Plugin Name: CAC Targeted AJAX Menu Items
 * Plugin URI: https://github.com/bangerkuwranger
 * Description: Creates a custom post type that can display posts on any other page or post without reloading the page. Loading this content can be done via menu items OR links generated by a shortcode. Target location is created by a shortcode within a page or post.
 * Version: 0.0.1
 * Author: Chad A. Carino
 * Author URI: http://www.chadacarino.com
 * License: MIT
 */
/*
The MIT License (MIT)
Copyright (c) 2014 Chad A. Carino
 
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
 
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/

if ( ! function_exists('cac_ajax_menu_content') ) {

// Register Custom Post Type for content to be loaded
function cac_ajax_menu_content() {

	$labels = array(
		'name'                => 'AJAX Contents',
		'singular_name'       => 'AJAX Content',
		'menu_name'           => 'AJAX Content',
		'all_items'           => 'All AJAX Content',
		'view_item'           => 'View AJAX Content',
		'add_new_item'        => 'Add New AJAX Content',
		'add_new'             => 'Add New',
		'edit_item'           => 'Edit AJAX Content',
		'update_item'         => 'Update AJAX Content',
		'search_items'        => 'Search AJAX Content',
		'not_found'           => 'Not found',
		'not_found_in_trash'  => 'Not found in Trash',
	);
	$args = array(
		'label'               => 'ajaxmenucontent',
		'description'         => 'Create content to load dynamically here.',
		'labels'              => $labels,
		'supports'            => array( 'title', 'editor', ),
		'hierarchical'        => false,
		'public'              => true,
		'show_ui'             => true,
		'show_in_menu'        => true,
		'show_in_nav_menus'   => true,
		'show_in_admin_bar'   => true,
		'menu_position'       => 5,
		'can_export'          => true,
		'has_archive'         => false,
		'exclude_from_search' => true,
		'publicly_queryable'  => true,
		'rewrite'             => false,
		'capability_type'     => 'page',
	);
	register_post_type( 'ajaxmenucontent', $args );

}

// Hook into the 'init' action to register post type
add_action( 'init', 'cac_ajax_menu_content', 0 );

}

// Register Frontend Scripts
function cac_ajax_js() {

	wp_register_script( 'menuitemfunction', plugin_dir_url( __FILE__ ) . 'js/menu-item-function.js', array( 'jquery' ), '0.0.1', true );
	wp_enqueue_script( 'menuitemfunction' );

}

// Hook into the 'wp_enqueue_scripts' action
add_action( 'wp_enqueue_scripts', 'cac_ajax_js' );